### ISSUE TITLE
Didn't work, validation of google account failed 

### ISSUE THREAD

**Issue by ThoundsN** [munir131/attachment-downloader#10]
```
Enter the code from that page here: 4/twF41gClfys6SrAwY7WFACfLEFMsSH1JnIWZMrJW5tEbQkxMISh_Nj4
Error retrieving access token { FetchError: request to https://oauth2.googleapis.com/token failed, reason: connect ETIMEDOUT 172.217.160.74:443
    at ClientRequest.<anonymous> (E:\迅雷下载\gmail_bulk\attachment-downloader\node_modules\node-fetch\lib\index.js:1444:11)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://oauth2.googleapis.com/token failed, reason: connect ETIMEDOUT 172.217.160.74:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  config:
   { method: 'POST',
     url: 'https://oauth2.googleapis.com/token',
     data:
      'code=4%2FtwF41gClfys6SrAwY7WFACfLEFMsSH1JnIWZMrJW5tEbQkxMISh_Nj4&client_id=280431205846-gtd3mva42iv230vhas4do6hsdj5f0jbv.apps.googleusercontent.com&client_secret=X1tQT4lWJsKYAKjLCiTzF1A4&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&grant_type=authorization_code&code_verifier=',
     headers:
      { 'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'google-api-nodejs-client/3.1.0',
        Accept: 'application/json' },
     params: [Object: null prototype] {},
     paramsSerializer: [Function: paramsSerializer],
     body:
      'code=4%2FtwF41gClfys6SrAwY7WFACfLEFMsSH1JnIWZMrJW5tEbQkxMISh_Nj4&client_id=280431205846-gtd3mva42iv230vhas4do6hsdj5f0jbv.apps.googleusercontent.com&client_secret=X1tQT4lWJsKYAKjLCiTzF1A4&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&grant_type=authorization_code&code_verifier=',
     validateStatus: [Function: validateStatus],
     responseType: 'json' }
```

**Comment by munir131** [comment]
@ThoundsN Your error(connect ETIMEDOUT 172.217.160.74:443') shows that you have some internet issue. Try again it should work now.
