### ISSUE TITLE
BUG: 'length' of undefined

### ISSUE THREAD

**Issue by michaelcadilhac** [munir131/attachment-downloader#9]
I get the following error:
```
 node index.js --label TODL
TypeError: Cannot read property 'length' of undefined
    at /home/micha/src/attachment-downloader/index.js:186:34
    at arrayMap (/home/micha/src/attachment-downloader/node_modules/lodash/lodash.js:639:23)
    at Function.map (/home/micha/src/attachment-downloader/node_modules/lodash/lodash.js:9554:14)
    at pluckAttachment (/home/micha/src/attachment-downloader/index.js:180:22)
    at /home/micha/src/attachment-downloader/index.js:52:30
```

This fixed the error, but I don't know if it's the "correct" fix:
```
diff --git a/index.js b/index.js
index 418aeb0..4985763 100644
--- a/index.js
+++ b/index.js
@@ -178,7 +178,7 @@ function saveFile(fileName, content) {
 
 function pluckAttachment(mails) {
   return _.compact(_.map(mails, (m) => {
-    if (!m.data) {
+    if (!m.data || !m.data.payload.parts) {
       return undefined;
     }
     const attachment = {
```

**Comment by munir131** [comment]
@michaelcadilhac It will work temporarily. I will check this issue in the weekend.
